"""The failures the generation loop is expected to handle.

One hierarchy, in one module, because the retry loop's whole job is to tell these apart: a rejected
candidate is fed back to the model as the reason to try again, while a backend that could not be
reached is not something a better prompt fixes. A caller that wants neither distinction catches
``GenerationError``.

Nothing here is user-facing. ``RuleResult.fail_reason`` is copy shown to a person booking a court;
these messages are for a developer running the loop, and say as much as they can.
"""

from __future__ import annotations

__all__ = [
    "GenerationError",
    "LLMCallError",
    "RuleRejectedError",
    "RuleContractError",
    "SuiteRejectedError",
    "ManifestRejectedError",
]


class GenerationError(Exception):
    """Base for every failure in the generation package."""


class LLMCallError(GenerationError):
    """The model could not be reached, or answered with something that is not an answer.

    Carries the backend's own diagnostics — exit code, whatever it wrote on stderr — because the
    likely causes (the CLI is not installed, the session is not authenticated, the model id does not
    exist) are all invisible from the text of a completion that never arrived.
    """

    def __init__(
        self,
        detail: str,
        *,
        exit_code: int | None = None,
        stderr: str = "",
    ) -> None:
        super().__init__(detail)
        self.detail = detail
        self.exit_code = exit_code
        self.stderr = stderr


class RuleRejectedError(GenerationError):
    """The model answered, and what it produced is not acceptable rule source.

    ``reason`` is the safety validator's own message, kept verbatim: it names the construct and the
    line, which is exactly what the retry loop hands back to the model. Paraphrasing it here would
    cost the model the one detail that lets it fix the candidate.

    ``source`` is the fence-stripped candidate that was rejected — the thing the reason is *about*,
    so a caller does not have to reconstruct what the model actually said.
    """

    def __init__(self, reason: str, *, source: str) -> None:
        super().__init__(reason)
        self.reason = reason
        self.source = source


class RuleContractError(RuleRejectedError):
    """The source is *safe* and still unusable: it does not match the values it will be handed.

    A subclass rather than a sibling, because the retry loop's handling is identical — this is a
    candidate the Generator is asked to correct, carrying its own source and its own reason, and a
    caller that catches ``RuleRejectedError`` must catch this too or the defect it names walks
    straight past. What the separate type buys is that the loop can *say which gate* rejected the
    candidate: reporting a parameter-unit mistake as "the safety validator rejected the source"
    would be the same misreading that cost this project a full benchmark round when every Tester
    fixture failure was reported as the rule being wrong (``rule-engine.md``, "Every failure the
    first run recorded was the Tester's").

    Raised only by ``generator.generate_rule``, from ``param_contract.param_contract_findings`` —
    see that module for the contract and for why it is enforced here rather than at the manifest
    call.
    """


class SuiteRejectedError(GenerationError):
    """The Tester answered, and what it produced is not a usable pytest module.

    Named for the *suite* rather than the tests because pytest collects any class whose name starts
    with ``Test``: ``TestsRejectedError`` imported into a test module emits a collection warning on
    every run, for a class that is an exception and not a test.

    Separate from ``RuleRejectedError`` because the two are fixed by different agents: a rejected
    rule is regenerated by the Generator, a rejected test module by the Tester. Collapsing them
    would send the wrong feedback to the wrong model.

    This is *not* a safety verdict. Test source is deliberately not put through
    ``validate_source`` — see ``tester.py`` for why — so the only things checked are that it parses
    and that it contains a test to run. Both are cheap, and both catch a model that answered with
    prose before a sandbox run is spent discovering it.
    """

    def __init__(self, reason: str, *, source: str) -> None:
        super().__init__(reason)
        self.reason = reason
        self.source = source


class ManifestRejectedError(GenerationError):
    """The model answered, and what it produced is not an acceptable manifest.

    Raised after the rule has already passed the sandbox — the source is not in question, only
    the description of it. There is deliberately no fourth model call to correct one: the
    artifact worth keeping is the rule that already survived its own adversarial suite, and
    regenerating it to fix a label or a mismatched parameter name would throw that away for
    nothing wrong with it. A caller that catches this treats it as a job failure, not a retry
    (``rule-engine.md``, "The manifest call").

    ``payload`` is what the reason is about — the model's raw text for a parsing or field
    failure, the rule source itself for a signature-loading failure — the same role
    ``RuleRejectedError.source`` plays.
    """

    def __init__(self, reason: str, *, payload: str) -> None:
        super().__init__(reason)
        self.reason = reason
        self.payload = payload
