"""A deterministic, no-network ``LLMClient`` for driving the generation loop without a model.

``rule-engine.md``'s stub-client decision, and ``OVERVIEW.md``'s: **a stub generation client
serves CI**, the same split ``benchmark.py`` already draws by never running in CI itself. Two
things need this. First, the backend's own test suite exercises the whole job — enqueue, run,
write a ``generated_rule_types`` row, hoist it live — and none of that should cost a model call or
depend on a daemon or a network being reachable in CI. Second, once 7.9 wires a generation panel
into the UI, the E2E suite (``app/e2e``) needs to drive that panel against something that answers
in milliseconds and never flakes on rate limits — the same reasoning that makes sandbox auth
(``.claude/rules/identity-and-access.md``) exist.

``StubLLMClient`` sits at the exact same ``LLMClient`` seam every other client in this package
does, so every layer above it — the Generator, the Tester, the retry loop, the sandbox, the
backend's job runner — is the real one. Nothing downstream of ``complete`` can tell this client
from a real one except by the fact that it never fails for a reason a real backend would (a
timeout, a rate limit, an unreachable daemon) and never varies for a reason a real model would (two
identical calls always get the identical answer).

**Dispatch is by which agent is calling, never by guessing at the prompt.** ``generate_rule``,
``generate_tests`` and ``generate_manifest`` each send their own fixed ``SYSTEM_PROMPT`` —
imported here from ``.generator``, ``.tester`` and ``.manifest`` themselves, compared by exact
equality — so this client answers correctly no matter what the *user* turn says, which is the
only turn each agent's own ``build_*_prompt`` actually varies per call. A substring guess over the
prompt text would break the moment any system prompt was reworded, silently, since nothing would
fail until this client answered the wrong agent's turn with the wrong kind of code.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from . import generator, manifest, tester
from .errors import LLMCallError
from .llm import DEFAULT_MODEL, LLMResponse

__all__ = ["StubLLMClient"]


#: The rule this stub's Generator turn hands back on every attempt that is allowed to succeed.
#: Named unlike any hand-written canon rule (`rules.canon.MaxDurationRule`) precisely because the
#: two are easy to mistake for each other otherwise — this one only ever exists as
#: `generated_rule_types.human_code`, never as an import, and the name says so.
_STUB_RULE_SOURCE = '''\
from datetime import timedelta


class StubMaxDurationRule(BaseRule):
    """Bookings may not run longer than ``max_duration`` minutes. The bound is inclusive.

    Canned output of StubLLMClient (rules/generation/stub.py) — never itself generated by a
    model. It exists so the generation loop, the sandbox, and the backend's job runner can be
    exercised end to end without a network call, the same role rules/canon.py's MaxDurationRule
    plays as the hand-written reference this class is deliberately styled after.

    ``max_duration`` arrives as a plain integer number of minutes — the wire shape the manifest
    declares (``kind: "integer", unit: "minutes"``) and the shape an admin form submits — and is
    converted to a ``timedelta`` here, in the constructor, exactly as a real generated rule would:
    the adapter that builds a rule instance (``app.rule_catalog``) hands over validated params
    verbatim, with no unit-aware coercion of its own, so converting a unit-labelled parameter into
    the type the rule's own logic needs is the rule's job, not the adapter's.
    """

    def __init__(self, max_duration):
        if max_duration <= 0:
            raise ValueError(f"max_duration must be positive; got {max_duration!r}")
        self.max_duration = timedelta(minutes=max_duration)

    def evaluate(self, request, context):
        if request.duration > self.max_duration:
            return RuleResult.deny(
                "Bookings can be at most 2 hours long. Please shorten it and try again."
            )
        return RuleResult.allow()
'''

#: Rule source this stub's Generator turn hands back when asked to fail: it imports a module
#: outside `rules.safety.ALLOWED_IMPORTS`, so `validate_source` rejects it and `generate_rule`
#: raises `RuleRejectedError` — the same path a real model's unsafe candidate takes.
_UNSAFE_RULE_SOURCE = '''\
import os


class StubUnsafeRule(BaseRule):
    """Deliberately unsafe canned output — imports os, which the safety validator rejects."""

    def evaluate(self, request, context):
        return RuleResult.allow()
'''

#: The pytest module this stub's Tester turn hands back — written to pass in the real sandbox
#: against `_STUB_RULE_SOURCE` and nothing else, verified by
#: `rules/tests/test_stub.py::test_stub_rule_and_tests_pass_in_the_real_sandbox`.
_STUB_TEST_SOURCE = """\
from datetime import datetime, timedelta, timezone

import pytest
from candidate_rule import StubMaxDurationRule
from engine import (
    BookingRecord,
    BookingRequest,
    CalendarContext,
    Context,
    HistoryContext,
    LocalFrame,
    UserContext,
    Weekday,
)


def make_local_frame():
    return LocalFrame(
        day_start=datetime(2026, 7, 21, tzinfo=timezone.utc),
        day_end=datetime(2026, 7, 22, tzinfo=timezone.utc),
        week_start=datetime(2026, 7, 20, tzinfo=timezone.utc),
        week_end=datetime(2026, 7, 27, tzinfo=timezone.utc),
        month_start=datetime(2026, 7, 1, tzinfo=timezone.utc),
        month_end=datetime(2026, 8, 1, tzinfo=timezone.utc),
        weekday=1,
        start_minutes=720,
        end_minutes=780,
    )


def make_context(now, bookings=()):
    return Context(
        user=UserContext("user-1"),
        calendar=CalendarContext(week_starts_on=Weekday.MONDAY, now=now),
        local=make_local_frame(),
        history=HistoryContext(bookings=tuple(bookings)),
    )


def test_short_booking_passes():
    rule = StubMaxDurationRule(120)
    request = BookingRequest(
        "user-1",
        "court-1",
        datetime(2026, 7, 21, 12, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 13, 0, tzinfo=timezone.utc),
    )
    context = make_context(now=datetime(2026, 7, 21, 11, 0, tzinfo=timezone.utc))
    assert rule.evaluate(request, context).passed


def test_exact_limit_passes():
    rule = StubMaxDurationRule(120)
    request = BookingRequest(
        "user-1",
        "court-1",
        datetime(2026, 7, 21, 12, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 14, 0, tzinfo=timezone.utc),
    )
    context = make_context(now=datetime(2026, 7, 21, 11, 0, tzinfo=timezone.utc))
    assert rule.evaluate(request, context).passed


def test_one_second_over_the_limit_is_denied():
    rule = StubMaxDurationRule(120)
    request = BookingRequest(
        "user-1",
        "court-1",
        datetime(2026, 7, 21, 12, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 14, 0, 1, tzinfo=timezone.utc),
    )
    context = make_context(now=datetime(2026, 7, 21, 11, 0, tzinfo=timezone.utc))
    result = rule.evaluate(request, context)
    assert not result.passed
    assert result.fail_reason


def test_invalid_max_duration_raises_at_construction():
    with pytest.raises(ValueError):
        StubMaxDurationRule(0)


def test_fails_closed_on_a_history_it_has_no_reason_to_read():
    # StubMaxDurationRule never reads context.history, so this is not a fail-closed probe in the
    # sense a rule that counts bookings needs — it is here to demonstrate the shape the real
    # Tester's system prompt asks for, on a rule simple enough that the probe cannot fail.
    rule = StubMaxDurationRule(120)
    request = BookingRequest(
        "user-1",
        "court-1",
        datetime(2026, 7, 21, 12, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 13, 0, tzinfo=timezone.utc),
    )
    other_users_booking = BookingRecord(
        "someone-else",
        "court-1",
        datetime(2026, 7, 21, 9, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 10, 0, tzinfo=timezone.utc),
    )
    context = make_context(
        now=datetime(2026, 7, 21, 11, 0, tzinfo=timezone.utc),
        bookings=(other_users_booking,),
    )
    assert rule.evaluate(request, context).passed


def test_evaluate_returns_a_rule_result():
    rule = StubMaxDurationRule(120)
    request = BookingRequest(
        "user-1",
        "court-1",
        datetime(2026, 7, 21, 12, 0, tzinfo=timezone.utc),
        datetime(2026, 7, 21, 13, 0, tzinfo=timezone.utc),
    )
    context = make_context(now=datetime(2026, 7, 21, 11, 0, tzinfo=timezone.utc))
    result = rule.evaluate(request, context)
    assert hasattr(result, "passed")
    assert hasattr(result, "fail_reason")
"""

#: The manifest this stub's Manifest turn hands back for `_STUB_RULE_SOURCE`. `params` names
#: exactly `StubMaxDurationRule.__init__`'s one argument — `max_duration` — because
#: `generate_manifest`'s cross-check would reject anything else, canned response included.
_STUB_MANIFEST_SOURCE = json.dumps(
    {
        "label": "Maximum duration (stub)",
        "description": "Caps how long a single booking may run. Canned output of StubLLMClient.",
        "params": [
            {
                "name": "max_duration",
                "kind": "integer",
                "label": "Maximum duration",
                "unit": "minutes",
                "required": True,
                "minimum": 1,
            }
        ],
        "reads_history": False,
    }
)


@dataclass
class StubLLMClient:
    """A canned, deterministic ``LLMClient`` — no network, no subprocess, no clock, no randomness.

    Two independent axes control what it answers:

    ``fail_first_attempts`` — how many of this client's own Generator turns answer with
    :data:`_UNSAFE_RULE_SOURCE` before switching permanently to :data:`_STUB_RULE_SOURCE`. Zero
    (the default) means every Generator turn succeeds, so a job driven by a fresh client reaches
    ``AttemptOutcome.PASSED`` on its first attempt. A positive count is what makes a *retried* job
    reachable on demand — the acceptance requirement that a retried job's second Generator exchange
    carry the previous source and the failure text needs an attempt 1 that fails and an attempt 2
    that does not, and scripting that here is what the stream lead asked for in preference to
    making the loop itself non-deterministic. Counted per **instance**, not per process: construct
    a fresh ``StubLLMClient`` per job/run, exactly as ``RecordingClient`` is constructed fresh per
    run, and the count starts back at zero.

    ``always_unsafe`` — every Generator turn answers with :data:`_UNSAFE_RULE_SOURCE`, forever, so
    a job driven by this client exhausts its retry budget and fails outright with no
    ``generated_rule_types`` row written — the acceptance requirement for a failing generation.
    Mutually exclusive with ``fail_first_attempts`` in effect (a client that never stops failing
    has no "first N" to count past); ``always_unsafe`` wins if both are set, since it is the more
    literal reading of "make it fail" and is what a caller reaching for both at once most likely
    means.

    The Tester turn never varies: :data:`_STUB_TEST_SOURCE` only exercises
    :data:`_STUB_RULE_SOURCE`, which is the only rule this stub's Generator ever hands to a
    *successful* attempt, so there is exactly one Tester answer that ever needs to exist. The
    Manifest turn — a third call this client answers, made by callers driving 7.8's manifest step
    after the loop passes, not by the loop itself — never varies for the identical reason:
    :data:`_STUB_MANIFEST_SOURCE` describes :data:`_STUB_RULE_SOURCE` and only ever needs to.
    """

    fail_first_attempts: int = 0
    always_unsafe: bool = False

    #: Run state, not a third axis of configuration: it counts this instance's own Generator
    #: turns so `complete` can compare against `fail_first_attempts` above. Excluded from
    #: `__init__` (a caller has no business seeding it — `StubLLMClient(0, False, 5)` would
    #: silently start a "fresh" client mid-retry) and from `__repr__` (it is not part of what
    #: configures this client, only of what it remembers having done).
    _generator_calls: int = field(default=0, init=False, repr=False)

    def complete(self, *, system: str, prompt: str, model: str = DEFAULT_MODEL) -> LLMResponse:
        if system == generator.SYSTEM_PROMPT:
            self._generator_calls += 1
            unsafe = self.always_unsafe or self._generator_calls <= self.fail_first_attempts
            text = _UNSAFE_RULE_SOURCE if unsafe else _STUB_RULE_SOURCE
        elif system == tester.SYSTEM_PROMPT:
            text = _STUB_TEST_SOURCE
        elif system == manifest.SYSTEM_PROMPT:
            text = _STUB_MANIFEST_SOURCE
        else:
            # Exact-equality dispatch (see the module docstring) means this is not a real model
            # struggling with an unfamiliar prompt — it is a caller invoking this stub with a
            # system prompt none of the three generation agents send, which is a caller bug and
            # is reported as one rather than answered with a guess.
            raise LLMCallError(
                "StubLLMClient does not recognise this system prompt: it matches none of "
                "generation.generator.SYSTEM_PROMPT, generation.tester.SYSTEM_PROMPT, or "
                "generation.manifest.SYSTEM_PROMPT."
            )

        # No token counts, no cost, no duration: this stub made no call anywhere, and reporting
        # zeros would claim a measurement that was never taken (the same argument every real
        # client's docstring makes for leaving a field it cannot report as None rather than 0).
        return LLMResponse(
            text=text,
            model=model,
            input_tokens=None,
            output_tokens=None,
            cost_usd=None,
            duration_ms=None,
        )
