"""identity schema

Creates Stream 2's five identity tables. Stream 1's ``bookings`` table is
deliberately absent — ``app.migration_filter`` keeps it out of autogenerate, and
Stream 4 folds it in once its model has settled.

Two of the unique indexes here are **partial**
(``uq_space_access_requests_pending`` and ``uq_space_invitations_pending``): they
constrain only rows with ``status = 'pending'``, so a user denied access once can
ask again and a revoked invitation can be reissued, while decided rows are kept
as history. Dropping the ``postgresql_where`` clause would turn them into plain
unique indexes and silently forbid both.

Revision ID: 456345a095a5
Revises:
Create Date: 2026-07-19 16:46:13.688564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "456345a095a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth0_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("last_login_at", UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth0_sub"),
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("archived_at", UtcDateTime(), nullable=True),
        sa.CheckConstraint("length(public_id) >= 20", name="ck_spaces_public_id_length"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "space_access_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                name="access_request_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("decided_at", UtcDateTime(), nullable=True),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(status = 'pending' AND decided_at IS NULL AND decided_by_user_id IS NULL)"
            " OR (status IN ('approved', 'denied')"
            " AND decided_at IS NOT NULL AND decided_by_user_id IS NOT NULL)",
            name="ck_space_access_requests_decision_complete",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_space_access_requests_space_status",
        "space_access_requests",
        ["space_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_space_access_requests_pending",
        "space_access_requests",
        ["space_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "space_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "member",
                name="membership_role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "revoked",
                name="invitation_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("accepted_at", UtcDateTime(), nullable=True),
        sa.CheckConstraint(
            "(status = 'accepted' AND accepted_at IS NOT NULL)"
            " OR (status IN ('pending', 'revoked') AND accepted_at IS NULL)",
            name="ck_space_invitations_accepted_at_matches_status",
        ),
        sa.CheckConstraint("email = lower(email)", name="ck_space_invitations_email_lowercase"),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_space_invitations_email_status", "space_invitations", ["email", "status"], unique=False
    )
    op.create_index(
        "uq_space_invitations_pending",
        "space_invitations",
        ["space_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "space_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "member",
                name="membership_role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_space_memberships_user", "space_memberships", ["user_id"], unique=False)
    op.create_index(
        "uq_space_memberships_space_user", "space_memberships", ["space_id", "user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_space_memberships_space_user", table_name="space_memberships")
    op.drop_index("ix_space_memberships_user", table_name="space_memberships")
    op.drop_table("space_memberships")
    op.drop_index(
        "uq_space_invitations_pending",
        table_name="space_invitations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_space_invitations_email_status", table_name="space_invitations")
    op.drop_table("space_invitations")
    op.drop_index(
        "uq_space_access_requests_pending",
        table_name="space_access_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_space_access_requests_space_status", table_name="space_access_requests")
    op.drop_table("space_access_requests")
    op.drop_table("spaces")
    op.drop_table("users")
    # ### end Alembic commands ###
