"""bookings table

Folds the booking store into Alembic. Until Stream 4 the ``bookings`` table was
created outside migrations (Stream 1 built it with ``Base.metadata.create_all``
on SQLite) and autogenerate was told to ignore it. Now one migration history owns
the whole schema, so this revision creates ``bookings`` on top of the identity
tables — columns, check constraints, the lookup index, and the overlap exclusion
constraint — matching ``app.db.models.Booking`` exactly.

``resource_id`` and ``user_id`` stay ``String(64)`` free text here, as they are
today; task 4.2 turns them into real foreign keys onto ``resources`` and
``users``.

The ``EXCLUDE USING gist`` constraint is the overlap invariant: no two confirmed
bookings on one resource may cover overlapping intervals. It needs the
``btree_gist`` extension for the ``resource_id WITH =`` equality term — the stock
gist opclasses cover the range ``&&`` but not equality on a scalar — so the
extension is created first. It is left in place on downgrade: an extension is a
database-wide capability rather than this table's data, and ``CREATE EXTENSION IF
NOT EXISTS`` keeps re-upgrading idempotent.

Revision ID: caafdd41ff19
Revises: 456345a095a5
Create Date: 2026-07-22 07:34:44.383216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import UtcDateTime
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "caafdd41ff19"
down_revision: Union[str, Sequence[str], None] = "456345a095a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("start_at", UtcDateTime(), nullable=False),
        sa.Column("end_at", UtcDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed",
                "cancelled",
                name="booking_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("cancelled_at", UtcDateTime(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("resource_id"), "="),
            (sa.literal_column("tsrange(start_at, end_at)"), "&&"),
            where=sa.text("status = 'confirmed'"),
            using="gist",
            name="ex_bookings_confirmed_no_overlap",
        ),
        sa.CheckConstraint(
            "(status = 'cancelled' AND cancelled_at IS NOT NULL)"
            " OR (status = 'confirmed' AND cancelled_at IS NULL)",
            name="ck_bookings_cancelled_at_matches_status",
        ),
        sa.CheckConstraint("start_at < end_at", name="ck_bookings_positive_duration"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bookings_resource_status_start",
        "bookings",
        ["resource_id", "status", "start_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookings_resource_status_start", table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
